# Generated by Django 6.0.4 on 2026-05-14 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_likepost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
