# Generated by Django 6.0.4 on 2026-07-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_riderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='car_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ride',
            name='car_image',
            field=models.ImageField(blank=True, upload_to='ride_cars/'),
        ),
        migrations.AddField(
            model_name='ride',
            name='car_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ride',
            name='car_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='recurring_days',
            field=models.CharField(blank=True, help_text='Comma-separated days, for example: monday,tuesday,wednesday', max_length=100),
        ),
        migrations.AddField(
            model_name='ride',
            name='trip_type',
            field=models.CharField(choices=[('single', 'Single trip'), ('recurring', 'Recurring trip')], default='single', max_length=20),
        ),
    ]
