# Generated by Django 6.0.4 on 2026-07-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_car_brand_ride_car_image_ride_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='recurring_days',
            field=models.CharField(blank=True, help_text='Comma-separated days, for example: monday,tuesday,wednesday', max_length=100),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='trip_type',
            field=models.CharField(choices=[('single', 'Single trip'), ('recurring', 'Recurring trip')], default='single', max_length=20),
        ),
    ]
