# Generated by Django 6.0.4 on 2026-07-18 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_riderequest_preferred_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='riderequest',
            name='unique_passenger_ride_request',
        ),
        migrations.AddField(
            model_name='riderequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='declined_ride_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rides.ride'),
        ),
    ]
